spring:
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
  datasource:
    platform: postgres
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:users;NON_KEYWORDS=USER
    username: usr
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    flyway:
      schemas: users
      locations: classpath:db/migration
    jpa:
      show-sql: true
      generate-ddl: false
      properties:
        hibernate:
          ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

